import { MathJax, MathJaxContext } from 'better-react-mathjax'


# Promises

A `Promise` is an object in JavaScript that represents the eventual completion or failure of an asynchronous operation and its resulting value. It may be a good idea to first review async vs sync if you haven't yet. 

Another way to say what a `Promise` is, is it's effectively a returned object to which you **attach** callbacks, not passing callbacks into a function. Imagine a function - createAudioFileAsync() - which asynchronously generates a sound file given a config record and two callback functions - one called if the audio file is successfully created, and the other called if an error occurs. Here's how it would look possibly:

```js
function successCallback(result) {
    print(`Audio file read at URL: ${result}`);
}
function failureCallback(error) {
    print(`Error generating audio file: ${error}`);
}
createAudioFileAsync(audioSettings, successCallback, failureCallback);

//Now if we want to rewrite it so createAudioFileAsync returns a promise instead, you would attach your callbacks to it (rather than pass them into the function):

createAudioFileAsync(audioSettings).then(successCallback, failureCallback);

//this has several advantages. Let's explore them
```

The latter form, as a promise, has these advantages:

<ul>
<li> Gaurantees: unlike the passed-in callbacks, a promise comes with gaurantees namely, callbacks added with `then()` will never be run before the completion of the current run of the JavaScript event loop. </li>
<li> Also gaurantees that the callbacks will be used even if they were added after the success or failure of the async operation that the promise represents.</li>
<li> Lastly, it gaurantees that multiple callbacks may be added by calling `then()` several times. Each will be invoked one after another, in insertion order.</li>
</ul>

One other great feature of promises is chaining: the idea of executing two or more async operations back to back, where each operation starts when its previous operation succeeds, with the result from the previous step - this is done via a promise chain: (note that `then()` returns a new promise, different than the original):

```js
const promise1 = doSomething();
const promise2 = promise.then(successCallback, failureCallback);
```

Note that there are optional arguments to `then`: 
`doSomething().then(function (result) { return doSomethingElse(result); }).then(function (finalResult) {print(`Got the final result: ${finalResult}`); }).catch(failureCallback);`
The portion `.catch(failureCallback)` is equivalent to `.then(null, failureCallback)`.

This can be shortened using arrow functions: `doSomething().then( (result) => doSomethingElse(result)).then ( (finalResult) => { print(`Got the final result: ${finalResult}`); }).catch(failureCallback);`

A rule of thumb is whenever your operation encounters a promise, return it and defer its handling to the next `then` handler. Never omit returning a promise.

Note that you can also chain after a catch - just call `.then()` after `.catch(() => {...})`, this lets actions occur even after an action fails in the original chain. You can also nest promise chains, however, it gets a little complicated to read.

The `Promise` can be in one of 3 states: pending (initial state, neither fulfilled nor rejected), fulfilled (meaning that the operation was completed successfully), and rejected (the operation has failed). The **eventual** state of a pending promise can either be fulfilled with a value, or rejected with a reason (error). When either of these happens, the associated handlers queued up by a promise's `then` method are called. A promise is said to be **settled** if it's either fulfilled or rejected, but at least not pending.

![promisespic](/img/promises.png)

There are several static methods as well as instance methods. Instance methods use the "Microtask queue". Let's see a basic example of calling such functions:

```js
const firstPromise = new Promise( (resolve, reject) => {
    //resolve(...) will be called if what we were doing (in async) is successful, and reject(...) if it failed.
    //let's use 'setTimeout(...) to simulate async code. In real usage, one would probably be using something like XHR or an HTML API

    setTimeout( () => {
        resolve("Success");
    }, 250);
});

firstPromise.then((successMessage) => {
    //successMessage is whatever passed in the resolve(...) function above
    print(`Good. ${successMessage}`);
});
```

Overall, it's good to understand the basic premise of promises and imagine how one can use it. The topic can go quite deep and this is only scratching the surface. 
